puremvc.define({name:'drawsomething.AppConstants'},{},{
	CORE_NAME:'DrawSomething',
	STARTUP:'startup',
	CONNECT_SOCKET:'connect_socket',//链接socket
	CONNECT_SUCCESS:'connect_success',//socket链接成功
	START_GAME:'start_game',//房主开启游戏
	GAME_STARTING:'game_starting',//开始游戏
	URS_LOGIN_SUCCESS:'urs_login_success',//urs登录成功
	URS_UNLOGIN:'urs_unlogin',
	GET_ROLELIST:'get_rolelist',
	GET_ROLELIST_SUCCESS:'get_rolelist_success',
	CHECK_LOGIN:'check_login',
	LOGINED:'logined',
	UNLOGIN:'unlogin',
	ROLE_CONFIRM:'role_confirm',//选择角色
	JOIN_ROOM:'join_room',
	BROADCAST_ROOMINFO:'broadcast_roominfo',
	BROADCAST_JOIN:'broadcast_join',
	BROADCAST_READY:'broadcast_ready',//广播准备信息
	READY:'ready',//准备
	DRAWING:'drawing',//绘画中
	DRAWING_HANDLE:'drawing_handle',
	DELETE:'delete',
	ANSWER_INFO:'answer_info',
	SEND_MSG:'send_msg',//回答问题
	RECEIVE_MSG:'receive_msg',
	RECEIVE_HINT:'receive_hint',//接收提示
})