// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distribute.proto

package com.netease.pangu.distribution.proto;

public final class GameDistributedProto {
  private GameDistributedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distribution_MethodRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distribution_MethodRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distribution_Worker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distribution_Worker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distribution_Worker_SysEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distribution_Worker_SysEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distribution_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distribution_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020distribute.proto\022\014distribution\032\031google" +
      "/protobuf/any.proto\"Y\n\rMethodRequest\022\020\n\010" +
      "beanName\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\"\n\004ar" +
      "gs\030\003 \003(\0132\024.google.protobuf.Any\"\227\001\n\006Worke" +
      "r\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\014\n\004name\030\003 \001(" +
      "\t\022\r\n\005count\030\004 \001(\005\022*\n\003sys\030\005 \003(\0132\035.distribu" +
      "tion.Worker.SysEntry\032*\n\010SysEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\",\n\013RpcResponse\022" +
      "\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2U\n\020AppMas" +
      "terService\022A\n\014addAppWorker\022\024.distributio",
      "n.Worker\032\031.distribution.RpcResponse\"\0002T\n" +
      "\020AppWorkerService\022@\n\004call\022\033.distribution" +
      ".MethodRequest\032\031.distribution.RpcRespons" +
      "e\"\000BG\n$com.netease.pangu.distribution.pr" +
      "otoB\024GameDistributedProtoP\001\210\001\001\242\002\003HLWb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_distribution_MethodRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distribution_MethodRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distribution_MethodRequest_descriptor,
        new java.lang.String[] { "BeanName", "MethodName", "Args", });
    internal_static_distribution_Worker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distribution_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distribution_Worker_descriptor,
        new java.lang.String[] { "Ip", "Port", "Name", "Count", "Sys", });
    internal_static_distribution_Worker_SysEntry_descriptor =
      internal_static_distribution_Worker_descriptor.getNestedTypes().get(0);
    internal_static_distribution_Worker_SysEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distribution_Worker_SysEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_distribution_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_distribution_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distribution_RpcResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
