// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distribute.proto

package com.netease.pangu.distribution.proto;

public interface MethodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distribution.MethodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string beanName = 1;</code>
   */
  java.lang.String getBeanName();
  /**
   * <code>optional string beanName = 1;</code>
   */
  com.google.protobuf.ByteString
      getBeanNameBytes();

  /**
   * <code>optional string methodName = 2;</code>
   */
  java.lang.String getMethodName();
  /**
   * <code>optional string methodName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>repeated .google.protobuf.Any args = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getArgsList();
  /**
   * <code>repeated .google.protobuf.Any args = 3;</code>
   */
  com.google.protobuf.Any getArgs(int index);
  /**
   * <code>repeated .google.protobuf.Any args = 3;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated .google.protobuf.Any args = 3;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any args = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getArgsOrBuilder(
      int index);
}
